### ISSUE TITLE
Remove exception logic

### ISSUE THREAD

**Issue by smudge202** [danielcirket/SimpleContainer#5]
No arguments! :)

**Comment by danielcirket** [comment]
No arguments about that here, this was a poor design decision on my part, null check > exceptions. I generally dislike exceptions myself so have no idea why I even used them in this to be honest.

**Comment by danielcirket** [comment]
Done, see commit: be312166c3f83edddd88915ac482b0b046f32247

**Comment by smudge202** [comment]
Was this reopened because there is some exception logic elsewhere I hadn't come across yet? Otherwise, totally agree that it addresses the issue, don't be afraid to close the issues. :) :shipit:

**Comment by danielcirket** [comment]
Closed by accident initially, was going to keep it open until you had a chance to take a look through the details.
