### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by herecydev** [danielcirket/SimpleContainer#8]
There's quite a few regions scattered over what seems like important fields and methods.

Regions typically are used to cover auto generated code and things that generally don't mean a great deal (but are necessary).

My suggestion is to remove them.

**Comment by danielcirket** [comment]
Done, see: be312166c3f83edddd88915ac482b0b046f32247 I have a habit of putting a region around fields, properties, methods, and events. But there are so few in this its definitely unnecessary

**Comment by smudge202** [comment]
@herecydev works with me, pretty sure he'll complain about the `IContainer` region but just because we whinge, doesn't mean we're right. :D

**Comment by herecydev** [comment]
Thanks for [the shoutout!](https://youtu.be/1wEdlX50y78?t=6m15s)

Smokes his cigarette...

![](http://makepixelart.com/peoplepods/files/images/1649929.resized.png)

But definitely agree, much better than last time; using meaningful regions instead of generic grouping.
