### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by danielcirket** [danielcirket/SimpleContainer#9]

**Comment by smudge202** [comment]
The site I typically use is this one: http://choosealicense.com/licenses/ but googling for license comparisons should serve you well.

**Comment by smudge202** [comment]
Some more info on not having a licence by Jeff Atwood: http://blog.codinghorror.com/pick-a-license-any-license/

**Comment by danielcirket** [comment]
So I guess looking at the first link the Apache license seems to make sense, I'll do some actual research though before deciding.

Do you have any recommendations from your experience?

**Comment by smudge202** [comment]
Apache would be a safe (albeit over-protective) bet for this kind of project. Something you're primarily using as a learning aid, but there may be some possibility of the project becoming more one day. The alternatives would either be Public Domain, or more likely GPL. Public Domain would mean "meh, do what you want with this", whilst GPL would be "do what you want with this, but no one can make money from it".

I'm not suggesting it as a _good_ thing, but I simply go with Apache all the time unless the company I'm working for interferes.
